# Generated by Django 6.0.2 on 2026-03-10 12:53

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='Nama Toko/Customer')),
                ('email', models.EmailField(blank=True, max_length=31, null=True)),
                ('phone_number', models.CharField(max_length=15, verbose_name='No HP')),
                ('address', models.CharField(blank=True, max_length=127, null=True, verbose_name='Alamat')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Non Aktif')], default='ACTIVE', max_length=10)),
                ('segment', models.CharField(choices=[('NEW', 'New Customer'), ('REGULAR', 'Regular'), ('VIP', 'VIP')], default='NEW', max_length=10)),
                ('total_transactions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_transaction', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_pic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Sales PIC')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('order_status', models.CharField(choices=[('REQUESTED', 'Mengajukan'), ('IN_PROGRESS', 'Diproses'), ('IN_SHIPPING', 'Diantar'), ('DELIVERED', 'Diterima'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='REQUESTED', max_length=15)),
                ('total_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('date_delivered', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('ACCOUNT', 'Account')], max_length=7)),
                ('payment_status', models.CharField(choices=[('UNINITIATED', 'Uninitiated'), ('UNPAID', 'Unpaid'), ('IN_CHECKING', 'In Checking'), ('PAID', 'Paid')], default='UNINITIATED', max_length=15)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_troubled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.customer')),
                ('who_inputs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_inputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('CREATED', 'Dibuat'), ('UPDATED', 'Diperbarui'), ('STATUS_CHANGED', 'Status Diubah'), ('CANCELLED', 'Dibatalkan')], max_length=20)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'product_variant'), name='order cannot have duplicate order items with the same variant')],
            },
        ),
    ]
