# Generated by Django 6.0.2 on 2026-03-02 14:51

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('email', models.EmailField(max_length=31, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=127, null=True)),
                ('last_transaction', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_PROGRESS', 'In Progress'), ('IN_SHIPPING', 'In Shipping'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], max_length=15)),
                ('total_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('date_delivered', models.DateField(null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('ACCOUNT', 'Account')], max_length=7)),
                ('payment_status', models.CharField(choices=[('UNINITIATED', 'Uninitiated'), ('UNPAID', 'Unpaid'), ('IN_CHECKING', 'In Checking'), ('PAID', 'Paid')], max_length=15)),
                ('payment_due_date', models.DateField(null=True)),
                ('payment_date', models.DateField(null=True)),
                ('is_troubled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.customer')),
                ('who_inputs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_inputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'product_variant'), name='order cannot have duplicate order items with the same variant')],
            },
        ),
    ]
