# Generated by Django 6.0.2 on 2026-03-10 10:55

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('unit', models.CharField(max_length=7)),
                ('qty_in_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('last_restocked', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'Nama supplier sudah terdaftar di sistem.'}, max_length=63, unique=True)),
                ('email', models.EmailField(max_length=31, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=127, null=True)),
                ('last_transaction', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(null=True)),
                ('who_inputs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_production_inputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('SOFT', 'Soft'), ('HARD', 'Hard')], max_length=7)),
                ('size_grams', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qty_in_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product_type', 'size_grams'), name='unique combination of product_type and size_grams as each variant')],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('receive_date', models.DateField(default=datetime.date.today)),
                ('who_inputs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_inputs', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DailyProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.dailyproduction')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_production_items', to='inventory.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('daily_production', 'product_variant'), name='within a single daily production, there cannot be duplicate variants')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.rawmaterial')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('purchase', 'raw_material'), name='uniqueness of raw_material within a purchase')],
            },
        ),
        migrations.CreateModel(
            name='DailyProductionRawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', to='inventory.dailyproduction')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_production_raw_items', to='inventory.rawmaterial')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('daily_production', 'raw_material'), name='within a single daily production, there cannot be duplicate raw materials')],
            },
        ),
    ]
