# Generated by Django 5.2.12 on 2026-03-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(error_messages={'unique': 'Nama supplier sudah terdaftar di sistem.'}, max_length=63, unique=True),
        ),
    ]
