# Generated by Django 6.0.2 on 2026-03-02 14:51

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=7)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'type'), name='uniqueness of name within the same entry type')],
            },
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(null=True)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.entrycategory')),
                ('who_inputs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_inputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
