# Generated by Django 6.0.2 on 2026-03-10 12:53

import apps.accounts.models
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(error_messages={'unique': 'Nomor telepon sudah terdaftar dalam sistem'}, max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Nomor telepon minimal terdiri dari 10 angka'), django.core.validators.RegexValidator('^[0-9]+$', message='Nomor telepon hanya boleh memuat angka, tanpa spasi, dash (-), ataupun tambah (+)')])),
                ('address', models.CharField(blank=True, max_length=127)),
                ('first_name', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Nama depan hanya boleh terdiri dari huruf alfabet dan spasi')])),
                ('last_name', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Nama belakang hanya boleh terdiri dari huruf alfabet dan spasi')])),
                ('avatar', models.ImageField(null=True, upload_to=apps.accounts.models.Account.get_upload_target)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('togglestatus_account', 'Can activate and deactivate account'), ('changepassword_account', 'Can change account password')],
            },
        ),
    ]
