# Generated by Django 6.0.2 on 2026-03-04 04:58

from django.db import migrations
from django.contrib.auth.management import create_permissions
from django.apps import apps as global_apps

def setup_groups_perms(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Register groups & correspondence to existing permissions content type & codename here
    # The map should contain group name as key, paired with list of 2-tuples as value
    # The 2-tuple contains the app_label and codename, representing the permission associated to the group in key
    # The codename follows the following format: [operation (add/view/change/delete)]_[object name in lowercase]
    # E.g. change_dailyproduction to refer to permission to update DailyProduction model
    
    group_perms = {
        'Sales': [
            ('orders', 'add_order'),   
            ('orders', 'view_order'),
            ('orders', 'change_order'),
            ('orders', 'delete_order'),

            ('orders', 'add_customer'),
            ('orders', 'view_customer'),
            ('orders', 'change_customer'),
            ('orders', 'delete_customer'),
        ],
        'Warehouse': [
            ('inventory', 'add_dailyproduction'),
            ('inventory', 'view_dailyproduction'),
            ('inventory', 'change_dailyproduction'),
            ('inventory', 'delete_dailyproduction'),
            ('inventory', 'add_purchase'),
            ('inventory', 'view_purchase'),
            ('inventory', 'change_purchase'),
            ('inventory', 'delete_purchase'),
        ],
        'Finance': [

            ('finance', 'add_entrycategory'),
            ('finance', 'view_entrycategory'),
            ('finance', 'change_entrycategory'),
            ('finance', 'delete_entrycategory'),

            ('finance', 'add_financeentry'),
            ('finance', 'view_financeentry'),
            ('finance', 'change_financeentry'),
            ('finance', 'delete_financeentry'),

            ('orders', 'view_customer'),
        ]
    }

    for app_config in global_apps.get_app_configs():
        create_permissions(app_config, verbosity=0)

    for group_name, permissions in group_perms.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        
        for app_label, codename in permissions:
            try:
                perm = Permission.objects.get(
                    codename=codename, 
                    content_type__app_label=app_label
                )
                group.permissions.add(perm)
            except Permission.DoesNotExist:
                print(f'Warning: permission {app_label}.{codename} does not exist')

def rollback(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group_names = ['Sales', 'Warehouse', 'Finance']
    Group.objects.filter(name__in=group_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        # Essential core dependencies
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        
        # Latest migration of each application
        ('accounts', '0001_initial'),
        ('finance', '0001_initial'),
        ('inventory', '0002_seed_raw_materials_and_variants'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_groups_perms, reverse_code=rollback)
    ]