# Generated by Django 6.0.2 on 2026-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearuser',
            name='address',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
