# Generated by Django 6.0.2 on 2026-03-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('togglestatus_account', 'Can activate and deactivate account')]},
        ),
    ]
