# Generated by Django 6.0.2 on 2026-03-04 04:58

from django.db import migrations
from django.contrib.auth.management import create_permissions
from django.apps import apps as global_apps

def setup_rbac(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # to register permission into a group / role, insert the codename in the list paired with the corresponding group / role key
    # permission codename syntax: [app_label].[view/add/change/delete]_[classnameinlowercase]
    # example: permission to create an 'Order' within application whose app_label = 'orders': orders.add_order
    # another example: perm to edit 'DailyProductionItem' within application whose app_label = 'inventory': inventory.edit_dailyproductionitem 

    role_permissions = {
        'Sales': [
            ('orders', 'add_order'),   
            ('orders', 'view_order'),
            ('orders', 'change_order'),
            ('orders', 'delete_order'),           
        ],
        'Warehouse': [
            ('inventory', 'add_dailyproduction'),
            ('inventory', 'view_dailyproduction'),
            ('inventory', 'change_dailyproduction'),
            ('inventory', 'delete_dailyproduction'),
            ('inventory', 'add_purchase'),
            ('inventory', 'view_purchase'),
            ('inventory', 'change_purchase'),
            ('inventory', 'delete_purchase'),
        ],
        'Finance': [
            ('finance', 'add_entrycategory'),
            ('finance', 'view_entrycategory'),
            ('finance', 'change_entrycategory'),
            ('finance', 'delete_entrycategory'),
        ]
    }

    for app_config in global_apps.get_app_configs():
        create_permissions(app_config, verbosity=0)

    for role, permissions in role_permissions.items():
        group, _ = Group.objects.get_or_create(name=role)
        
        for app_label, codename in permissions:
            try:
                perm = Permission.objects.get(
                    codename=codename, 
                    content_type__app_label=app_label
                )
                group.permissions.add(perm)
            except Permission.DoesNotExist:
                print(f'Warning: permission {app_label}.{codename} does not exist')

def rollback_rbac(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    roles = ['Sales', 'Warehouse', 'Finance']
    Group.objects.filter(name__in=roles).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_gearuser_address'),
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_rbac, reverse_code=rollback_rbac)
    ]