# Generated by Django 6.0.2 on 2026-03-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('togglestatus_account', 'Can activate and deactivate account'), ('changepassword_account', 'Can change account password')]},
        ),
    ]
