# Generated by Django 6.0.2 on 2026-03-05 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_setup_rbac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gearuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gearuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Nama depan hanya boleh terdiri dari huruf alfabet dan spasi')]),
        ),
        migrations.AlterField(
            model_name='gearuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Nama belakang hanya boleh terdiri dari huruf alfabet dan spasi')]),
        ),
        migrations.AlterField(
            model_name='gearuser',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'Nomor telepon sudah terdaftar dalam sistem'}, max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Nomor telepon minimal terdiri dari 10 angka'), django.core.validators.RegexValidator('^[0-9]+$', message='Nomor telepon hanya boleh memuat angka, tanpa spasi, dash (-), ataupun tambah (+)')]),
        ),
    ]
